spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.200:3306/zjyd-peixun?characterEncoding=utf8&useUnicode=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 10000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1